### PR TITLE
Performance improvements

### PR DESCRIPTION
**Pull request by severinraez**
For our usecase (generating various QR codes with dimensions 65x65), `RQRCode::QRCode.new` runs in 1.8 seconds before and in 0.9 seconds after these changes.

This is a follow up to https://github.com/whomwah/rqrcode/issues/145 , fixing the correct root cause - if you merge this, It'd be great if you could publish a new version :)

### CODE REVIEW

**Comment by swifthand** [comment]
Hi @severinraez,

I recently encountered issues related to these rules. Rules 1, 3 and 4 do not match the specification at all. I have opened an issue (#37) with an initial question about this, and I have working solution along with some tests. My question is "Is this a bug, or is there a reason for the incorrect behavior, such as reflecting an older version of the ISO Spec?" and if the answer is "This is a bug", I will be opening a Pull Request.

My changes would clash with this PR.

I am not the best at performance optimization. If my changes are deemed useful, I would welcome your input, as I only did the bare minimum to correct the penalty score behavior.

**Comment by severinraez** [comment]
Hi @swifthand 

Thanks for the ping. I'd be happy to help. I'll be on leave from next week to the end of August though.

Tangentially, if it's decided to move forward with both PRs, I might contribute a performance test that can help to measure performance impacts of code changes for larger QR codes. I think I could extract and anonymize some data from our usecase.  Maybe we could build on top of https://github.com/whomwah/rqrcode_core/blob/master/test/benchmark.rb .

**Comment by whomwah** [comment]
@severinraez thanks for your work and sorry its taken so long to reply. After an initial back and forth on https://github.com/whomwah/rqrcode_core/issues/37 it kind of stalled. The gist of the conversation was me explaining that this is first time this issue has come up in all the years of the gem, so whilst it's valid and helpful. I guess "most" people are ok so I need to balance the risk of a core change based on the current install base.

You have alluded to some big performance gains, but I would need some more proof. The test suite is not enormous but adding more is always helpful and some performance tests across small and large QR codes to make sure this improvement works across the board would also be helpful?

Let me know if this is something you are interested in. No problem if not.

**Comment by severinraez** [comment]
@whomwah we are planning to explore an alternative solution in the next months. If that does not work out, I'd still be motivated to add performance specs so we can proof the speedup and make sure things don't get slower by accident in the future.

What we're trying to do is to use the `qrencode` binary (https://linux.die.net/man/1/qrencode), with that approach the encoding time is around 100ms, but it remains to be seen whether the resulting codes are still valid after post processing (we overlay an image in the center).

**Comment by whomwah** [comment]
Closing for the time being, maybe to open at a later date.

**Pull request closed without merging**
