### PR TITLE
Fix 'do your own rendering' example.

### PR DESCRIPTION
**Pull request by jamesneal**
I'm doing my own rendering, and realized the example in the README was a little incorrect.  This fixes it. :)

Thanks for the library.

### CODE REVIEW

**Review by whomwah — DISMISSED** [review]
Well spotted @jamesneal I changed the interface a while back and must have forgot the README. Sometimes it takes someone else to notice. 👍

**Comment by whomwah** [comment]
@jamesneal If you wouldn't mind updating the CHANGELOG too (in unreleased section) that will save me a job later down the line. Thanks.

**Comment by jamesneal** [comment]
> 

Sure thing!

**Review by whomwah — APPROVED** [review]
👌

**Pull request merged**
